language: node_js
node_js:
- '6.1'
deploy:
  provider: heroku
  api_key:
    secure: QBshVyU6xWmkRNrLPnpilUtRZAVaD5ZWv1EC1tINijVu7GDRfV+0+K4Dxo+yp33uyLWaO73C3nTvhKHZP7KUjHkyySG9zBSJSL2MLqwhdZu2heIyRII42P4T5YYATco+s6rUjl31+mP3yqIB+vN2ODJ62YJ8DbdHOFo2zP7STblC/kJyt/keX9QEIdxODbC1AqfUD//9PIaBYP2l/o3kzoRxDHxJ98ppSdYtmuaprGITyCbb5WXgZQ4R+BPqjqmtB/qiZGqElBmQXnGa+CXmaNWo49ZOnjadqVydgpUyI4gtJ3d3VrcwLKUGLHjmyBwJrzImV3NVJ6YDuUBU3FBrVNQvJvIvn0GsuY8M/YJBPXcsJYsDzw8kRvBhwnIfAMiomUAT2XphSyZhG7vLg8KkHRF66XKYj8qYyV/rY4+RLXrFdhNEt6Q0eoV54pS1x6yVVE06UdYHU1uIDR14mooPY5L+gpS1+TPTe+ALcaao9BxSPCdU0s5JZs3CafTeQrzIDF+IZ3eVtdzFmWxvBlReccsScvwOHbVy3QmMLiNgt0/WRW2poZdMM6plc0mgrJlE52IKHzO/DiYe/OzVWWusqD+Jt2jbpyLws9J5cpg7fcNQ/YyAI5NFxXOCjvcr1hkq+EwKJc5RizdsOyyzPieyfHTzMh3+bBVP4Kx6RPU/rV8=
